language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install flake8"
  - "pip install -r requirements/requirements-test.txt"
# command to run tests
script:
  - "flake8 towers setup.py"
  - "nosetests --with-coverage --cover-erase --cover-package=towers --cover-html --cover-branches"

after_success:
  - "coveralls"
